line_length:
- 250 # warning
- 400 # error
disabled_rules:
- force_cast
- trailing_whitespace
excluded:
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift
- Source/*/ExcludedFile.swift
function_parameter_count:
- 14 # warning
- 20 # error


