# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK_App
	
  pod 'Alamofire'
  pod 'SwiftyJSON' 
  pod 'RealmSwift', '10.8.0-beta.2'
  pod 'Kingfisher', '~> 6.0.0'
  pod "SimpleAnimation"

end
